### ISSUE TITLE
UAX21 and UAX27 need updating — but how?

### ISSUE THREAD

**Issue by frivoal** [tobie/specref#347] opened 2017-04-05 17:51 UTC
The UAX21 and UAX27 entries are out of date. Not only are there later incarnations of the same documents, but also these documents have eventually been discontinued and their content merged to an other spec (Core Specification of the Unicode Standard). What should we do?

It makes sense to me to:
1. Update them to the latest standalone version
2. add an `obsoletedBy` key to point to the document that replaces them.

However, client software that read from specref do not currently support `obsoletedBy`. Should we just fix them? Should we mark it some other way?

--

issue raised from https://github.com/w3c/csswg-drafts/issues/1169#issuecomment-291779023
bikeshed issue about supporting `obsoletedBy`: https://github.com/tabatkins/bikeshed/issues/427

**Comment by tobie** [comment] 2017-04-05 20:23
IMHO, `obsoletedBy` only makes sense in cases where there's ambiguity as to which spec we now want to reference. In cases where it's obvious what new spec to use instead, maybe aliasing is the better option. What do you think? /cc @tabatkins, @marcoscaceres

**Comment by tabatkins** [comment] 2017-04-05 20:42
Aliasing might be sufficient, but in general it's often too strong - it means that no one can ever refer to the older version, even if they very intentionally want to.  (For example, to compare and contrast an older document with a newer one.)

My plan is to throw an error by default when you have an obsolete biblio ref, letting you know what you should be linking to, but give some syntax for suppressing that error and just linking to the obsolete thing.

**Comment by tobie** [comment] 2017-04-05 21:05
> Aliasing might be sufficient, but in general it's often too strong - it means that no one can ever refer to the older version, even if they very intentionally want to. (For example, to compare and contrast an older document with a newer one.)

Agreed.

> My plan is to throw an error by default when you have an obsolete biblio ref, letting you know what you should be linking to, but give some syntax for suppressing that error and just linking to the obsolete thing.

I didn't know you were planning to add syntax to suppress the error. That makes the distinction between obsolescence and aliasing worthwhile. So WFM.

Heads up that `obsoletedBy` returns an array of identifiers. Adding a few tests right now to see if we can provide some guarantees about the references these identifiers point to like we can with `aliasOf`.

**Comment by tobie** [comment] 2017-04-10 09:35
Guarantees added. See: [README](https://github.com/tobie/specref/blob/master/README.md#obsoleted-references).

**Comment by tabatkins** [comment] 2017-04-12 00:00
And Bikeshed now tracks and follows `obsoletes`/`obsoletedBy` data; using an obsolete biblio ref is a fatal error that tells you what to replace it with (following aliases/obsoletedBy transitively).

By the way, the following refs are marked as being obsolete, but the thing they claim should obsolete them doesn't exist in the db: 

* nic15392
* ien115
* ien119
* nic15390
* ien123
* ien133
* nic18640
* nic15389
* nic16238
* nic16239

**Comment by tobie** [comment] 2017-04-12 00:01
Wow. That is weird and should have been caught by the the test suite. Need to dig into this to find what the problem is.

**Comment by frivoal** [comment] 2017-04-14 06:25
Opened a [new issue](https://github.com/tobie/specref/issues/352) to follow up on https://github.com/tobie/specref/issues/347#issuecomment-293434102, which is a separate problem.

**Closed** 2017-04-14 06:39 UTC
